version: '3'
services:

  web: # Ruby on Railsが起動するコンテナ
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app # アプリケーションファイルの同期
    ports:
      - "3000:3000" # localhostの3000ポートでアクセスできるようにする
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db: # MySQLが起動するコンテナ
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql # データの永続化
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 'rails-d-ver1_development' #Ruby on Railsのdevelopment環境名をmy SQLにも設定

volumes:
  mysql_data: # データボリュームの登録((アプリ名で登録されるのかな)
