source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails", "~> 3.4.2"

gem "sprockets", "~> 4.1.1"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.6.5"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails", "~> 1.1.5"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails", "~> 1.3.2"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails", "~> 1.1.1"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder", "~> 2.11.5"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", "~> 1.13.0", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem "msgpack", "~> 1.6.0"
gem "irb", "~> 1.4.2"
gem "reline", "~> 0.3.1"
gem "bindex", "~> 0.8.1"
gem "addressable", "~> 2.8.1"
gem "regexp_parser", "~> 2.6.0"
gem "xpath", "~> 3.2.0"
gem "childprocess", "~> 4.1.0"
gem "websocket", "~> 1.2.9"
gem "public_suffix", "~> 5.0.0"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", "~> 1.6.3", platforms: %i[ mri mingw x64_mingw ]
  gem "rubyzip", "~> 2.3.0"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console", "~> 4.2.0"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara", "~> 3.38.0"
  gem "selenium-webdriver", "~> 4.6.1"
  gem "webdrivers", "~> 5.2.0"

end

#機能実装用に追加
gem 'devise' # ユーザ登録
gem "refile", require: "refile/rails", :git => 'https://github.com/manfe/refile.git' # 画像投稿
gem "refile-mini_magick" # サイズ調整など画像加工
gem "bulma-rails" # CSSフレームワーク
gem "sassc-rails"
